#!/bin/bash
# Statusbar script for dwm
# time, sound, wifi, updates

# make icon variables available
source ~/.local/share/icons-in-terminal/icons_bash.sh

updates() {
  number="$(pacman -Qu | wc -l)"

  message="$fa_download $number"

  if [ "$number" -gt 0 ]
  then
    echo -e "$message |"
  else
    echo ""
  fi

}

fecha() {
  fecha="$(date +"%H:%M")"
  echo -e "$oct_clock $fecha"
}

user() {
  user="$(git config --global user.name)"
  echo -e "$oct_key $user"
}

battery() {
  bat_status="$(acpi -b | sed 's/.*: \([a-zA-Z]*\),.*/\1/gi')"
  bat_charge="$(acpi -b | grep -P -o '[0-9]+(?=%)')"

  # assign different icon depending on charge rate
  if [ "$bat_charge" -gt 90 ] 
  then
    bat_icon=$fa_battery
  elif [ "$bat_charge" -ge 70 ] 
  then
    bat_icon=$fa_battery_3
  elif [ "$bat_charge" -ge 50 ] 
  then
    bat_icon=$fa_battery_2
  elif [ "$bat_charge" -ge 30 ] 
  then
    bat_icon=$fa_battery_1
  elif [ "$bat_charge" -lt 20 ] 
  then
    bat_icon=$fa_battery_0
  fi

  echo -e "$bat_icon $bat_charge%"
}

while true; do
  xsetroot -name " $(updates) $(battery) | $(fecha) | $(user) "
  sleep 10s
done 
