#!/bin/bash
#
# Set brightness with xbacklight, but never go below 1 (as that's "off").
# this need to be linked to /usr/bin/ and make executable (chmod +x)

# Increment to use.
incr=5%

# Current value needs to be converted to integer for conditionals evaluation
cur_raw=$(xbacklight -get)
cur=${cur_raw%.*}

case "$1" in
	"up")
		if [ $cur -eq 0 ]; then
			xbacklight -set 10
		else
			xbacklight -inc $incr
		fi
	;;
	"down")
		if [ $cur -le 5 ]; then
			xbacklight -set 1
		else
			xbacklight -dec $incr
		fi
	;;
	*)
		echo "Unsupported: \"$1\""
		exit 1
esac

xbacklight -get

